__title__ = "boto3-fixtures"
__version__ = "0.0.1.b1"
__summary__ = ""
__author__ = "Charlie Mathews"
__author_email__ = "cmathews@mintel.com"
__maintainer__ = "Charlie Mathews"
__maintainer_email__ = "cmathews@mintel.com"
__uri__ = "https://github.com/mintel/boto3-fixtures"
