__title__ = "boto3-fixtures"
__version__ = "0.0.4b1"
__summary__ = "Python test fixtures for your local AWS cloud stack"
__author__ = "Charlie Mathews"
__author_email__ = "charlie@charliemathews.com"
__maintainer__ = "Charlie Mathews"
__maintainer_email__ = "charlie@charliemathews.com"
__uri__ = "https://github.com/alphachai/boto3-fixtures"
